### ISSUE TITLE
load bearing prompt typo?

### ISSUE THREAD

**Issue by jmhodges** [caesarHQ/textSQL#124]
Is the typo of "scientiest" (instead of "scientist") in the [table selection prompt](https://github.com/caesarHQ/textSQL/blob/6d1fd4fb16731f1f0f093100347a09d5d1ba46d8/api/app/api/utils/table_selection/table_selection.py#L23) a load-bearing one or correctable?

**Comment by matthewlouisbrockman** [comment]
good call, probably not too load-bearing but it all matters. fixed it!
