### ISSUE TITLE
I need help! I cant't find out  app.py file, how to run api  thanks

### ISSUE THREAD

**Issue by xiongzhenglong** [caesarHQ/textSQL#127]
![4a31dd7df64c2f0003036a41d2ad192](https://user-images.githubusercontent.com/19340413/232686401-ef3967e5-d839-40b5-bddf-a95930b8975c.png)
![5b9cd8f88a66e4ab2fac545f30dce91](https://user-images.githubusercontent.com/19340413/232686404-4bc245ae-1f7f-40d8-9ac1-eb0a88ada1fa.png)
![a87173446d648de46238cb948a93cac](https://user-images.githubusercontent.com/19340413/232686406-98f8781a-925d-4fc1-bcc0-21053b8bce8b.png)

I try to run init.py ，but fail . i'm beginner  thanks

**Comment by zaaath** [comment]
@xiongzhenglong Follow the instructions in [API README](https://github.com/caesarHQ/textSQL/blob/main/api/README.md):
 - Initialize an `.env` file with the contents of `.env.example` file in the `/api` folder
 - Paste your OpenAI key in `.env` file
 - Run the commands from [/api/scripts/setup.sh](https://github.com/caesarHQ/textSQL/blob/main/api/scripts/setup.sh) one by one from `/api` directory:
 - 1. python3.10 -m venv ./venv
 - 2. source venv/bin/activate
 - 3. pip install --upgrade pip
 - 4. cat requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 python -m pip install
 - Run the following command in the same virtual Python env: `./scripts/dev.sh`

This sequence got me started. Let me know if you run into any other issues.

**Comment by zaaath** [comment]
See #129
