### ISSUE TITLE
Parallelize multiple OpenAI requests to combat discrepancies with completions (even with temperature=0)

### ISSUE THREAD

**Issue by alex-sun-kuo** [caesarHQ/textSQL#36]
Large language model outputs are not deterministic, even when setting the temperature to 0. Therefore, the model may output different SQL queries given the same natural language queries. Some of these SQL queries may be incorrect (either not what the user is asking for, or straight up triggers an Exception).

We have retries (see function `text_to_sql_with_retry` in `api/app/api/utils.py`) to regenerate SQL queries until the language model produces a query that doesn't trigger an exception, but this results in higher latencies (not by a ton, but enough to be noticeable). One thing we could do is parallelize K requests to OpenAI for generating SQL, then have K results to iterate through right off the bat.

**Comment by asaprahul** [comment]
This would be game changing! thanks for working on this @alex-sun-kuo 
Would we also check the K completions for exceptions and retry them? What's your thinking around that? 
I think the current exception -> retry is powerful, especially with combatting column name hallucinations etc.

**Comment by alex-sun-kuo** [comment]
@asaprahul i would parallelize the first K attempts as a batch. so for example, run 3 completion requests in parallel. iterate through them, trying to execute them. the first generated query in this initial batch that executes without failure, return SQL query and results. if all K fail, take the first query that failed and its error message, and proceed with the retry logic on that one (not on all K)

**Comment by asaprahul** [comment]
solid. excited to try this out!

**Comment by alex-sun-kuo** [comment]
https://github.com/caesarHQ/textSQL/pull/41 done
