### ISSUE TITLE
bug: query in the URL should populate table and map 

### ISSUE THREAD

**Issue by asaprahul** [caesarHQ/textSQL#37]
Here is the URL for "Richest neighborhood in San Francisco" with the query as a URL param:
https://censusgpt.com/?s=Richest%20neighborhood%20in%20San%20Francisco

When this URL is opened, the app make a call to the backend and render the table and map with the returned data. Right now it only populates the search field with the query in the URL.

**Comment by tanujtiwari98** [comment]
Done
